all:
	clear
	gcc -Wall -o P1 P1.c
	gcc -Wall -o P2 P2.c
	gcc -Wall -o P3 P3.c
	gcc -Wall -o P4 P4.c
	gcc -Wall -o P5 P5.c
	gcc -Wall -o P6 P6.c
	gcc -Wall -o P7 P7.c
	gcc -Wall -o P8 P8.c
	gcc -Wall -o P9 P9.c
	gcc -Wall -o P10 P10.c
	gcc -Wall -o P11 P11.c
	gcc -Wall -o P12 P12.c
	gcc -Wall -o P13 P13.c
	gcc -Wall -o P14 P14.c
	gcc -Wall -o P15 P15.c
	gcc -Wall -o P16 P16.c
	gcc -Wall -o P17 P17.c
	gcc -Wall -o P18 P18.c
	gcc -Wall -o P19 P19.c
	gcc -Wall -o P20 P20.c